[package]
name = "rustfft-c-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustfftcffi"
crate-type = ["staticlib"]

[dependencies]
rustfft = "6.1.0"

[profile.release] 
opt-level = 3
debug = false
overflow-checks = false